#!/usr/bin/env python3
import argparse
import sys

from leagueTable import LeagueTable


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate league table from match results')
    parser.add_argument('--matches','-m', help='File containing match results. Defaults to stdin')

    args = parser.parse_args()

    if not args.matches:
        parser.print_help()
        sys.exit()

    LT = LeagueTable()
    for line in open(args.matches).readlines():
        LT.addMatch(line)

    c = 0
    for i  in list(LT):
        c += 1
        print ('%s. %s' %(c, i))
